spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  redis:
    host: 192.168.233.131
    port: 6379
  session:
    store-type: redis
server:
  servlet:
    session:
      timeout: 30m
