spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tMxWpw9FKqL2bbcMzf2
      secret-key: 4LOJ7TK9TG5qhlipeeZuFbsmsIHUx4
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: gulimall-linjingdong
  application:
    name: gulimall-third-party

server:
  port: 30000


