spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.233.131

gulimall:
  thread:
    core-size: 20
    keep-alive-time: 10
    max-size: 200

